package com.abctreinamentos;
// Generated 21 de jul de 2021 17:06:25 by Hibernate Tools 5.5.3.Final


/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long cdcurso;
	private String nomecurso;
	private long valor;
	private String url;

	public Curso() {
	}

	public Curso(long cdcurso, String nomecurso, long valor, String url) {
		this.cdcurso = cdcurso;
		this.nomecurso = nomecurso;
		this.valor = valor;
		this.url = url;
	}

	public long getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(long cdcurso) {
		this.cdcurso = cdcurso;
	}

	public String getNomecurso() {
		return this.nomecurso;
	}

	public void setNomecurso(String nomecurso) {
		this.nomecurso = nomecurso;
	}

	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	@Override
	public String toString() {
		return "Curso [cdcurso="+cdcurso+" nome=" +nomecurso+" valor="+valor+" url="+url+"]";
	}
	

}
