package com.abctreinamentos;
// Generated 21 de jul de 2021 17:06:25 by Hibernate Tools 5.5.3.Final

import java.math.BigInteger;

/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigInteger cpf;
	private BigInteger cdcurso;

	public PagamentoId(long cpf2, long cdcurso2) {
	}

	public PagamentoId(BigInteger cpf, BigInteger cdcurso) {
		this.cpf = cpf;
		this.cdcurso = cdcurso;
	}

	public BigInteger getCpf() {
		return this.cpf;
	}

	public void setCpf(BigInteger cpf) {
		this.cpf = cpf;
	}

	public BigInteger getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(BigInteger cdcurso) {
		this.cdcurso = cdcurso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagamentoId))
			return false;
		PagamentoId castOther = (PagamentoId) other;

		return ((this.getCpf() == castOther.getCpf())
				|| (this.getCpf() != null && castOther.getCpf() != null && this.getCpf().equals(castOther.getCpf())))
				&& ((this.getCdcurso() == castOther.getCdcurso()) || (this.getCdcurso() != null
						&& castOther.getCdcurso() != null && this.getCdcurso().equals(castOther.getCdcurso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCpf() == null ? 0 : this.getCpf().hashCode());
		result = 37 * result + (getCdcurso() == null ? 0 : this.getCdcurso().hashCode());
		return result;
	}

}
